server:
  port: 10000
  servlet:
    context-path: /portal
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 120.25.255.82:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gmall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 8235250
  application:
    name: portal
  thymeleaf:
    cache: false
  redis:
    host: 120.25.255.82
#  zipkin:
#    base-url: http://localhost:9411
#    discovery-client-enabled: false
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      probability: 1
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  # 读取映射文件
  type-aliases-package: com.a528854302.gmall.provider.entity
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增
feign:
  sentinel:
    enabled: true

#自己实现的文件上传配置
my-upload:
  uploadDir: d:/mytmp/ #文件上传文件夹,必须以/结尾
  access-url: /files/  #文件url访问路径,必须以/结尾