server:
  port: 88
spring:
  application:
    name: gateway-api
  redis:
    host: 121.36.197.225
    port: 6379
  #整合spring session配置
  session:
    store-type: redis
  cloud:
    nacos:
      discovery:
        server-addr: 121.36.197.225:8848
    gateway:
      routes:
        - id: provider-route # 服务提供者路由,注意该路由需要放在前面
          uri: lb://provider
          predicates:
            - Path=/api/provider/**
          filters:
            - RewritePath=/api/provider/(?<segment>.*),/provider/$\{segment}

        - id: renren-fast-route # renren-fast路由
          uri: lb://renren-fast
          predicates:
             - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: portal-route # 商城前台路由
          uri: lb://portal
          predicates:
            - Path=/portal/**
          filters:
            - RewritePath=/portal/(?<segment>.*),/portal/$\{segment}

        - id: auth-route # 认证路由
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*),/auth/$\{segment}

        - id: item-route # 服务提供者路由,注意该路由需要放在前面
          uri: lb://provider
          predicates:
            - Path=/item/**
          filters:
            - RewritePath=/item/(?<segment>.*),/files/$\{segment}

        - id: seckill-route # 认证路由
          uri: lb://seckill
          predicates:
             - Path=/seckill/**
          filters:
             - RewritePath=/seckill/(?<segment>.*),/seckill/$\{segment}