server:
  port: 9999
  servlet:
    context-path: /seckill
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 121.36.197.225:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gmall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 8235250
  application:
    name: seckill
  thymeleaf:
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: 121.36.197.225
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual #设置手动处理消息是否处理成功
  task:
    execution:
      pool:
        core-size: 5
        max-size: 30
  redis:
    host: 121.36.197.225
    port: 6379
#  zipkin:
#    base-url: http://localhost:9411
#    discovery-client-enabled: false
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      probability: 1
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  # 读取映射文件
  type-aliases-package: com.a528854302.gmall.seckill.entity
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  sentinel:
    enabled: true


