server:
  port: 8877
  servlet:
    context-path: /auth
    session:
      timeout: 30m
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 121.36.197.225:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gmall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 8235250
  application:
    name: auth
  thymeleaf:
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 121.36.197.225
    port: 6379
  #整合spring session配置
  session:
    store-type: redis
#  zipkin:
#    base-url: http://localhost:9411
#    discovery-client-enabled: false
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      probability: 1
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  # 读取映射文件
  type-aliases-package: com.a528854302.gmall.auth.entity
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  sentinel:
    enabled: true
